---
deployment:
  tasks:
    # 1. Khai báo đường dẫn đích
    - export DEPLOYPATH=/home/nhtamup/public_html/
    # 2. SAO CHÉP MÃ NGUỒN VÀO THƯ MỤC ĐÍCH
    - /bin/cp -R * $DEPLOYPATH
    # 3. Chuyển thư mục làm việc sang thư mục đích
    - cd $DEPLOYPATH
    # 5. Cấp quyền (Đã đúng)
    - chmod -R 755 $DEPLOYPATH/storage
    - chmod -R 755 $DEPLOYPATH/bootstrap/cache
