# .cpanel.yml
---
deployment:
  tasks:
    - export DEPLOYPATH=/home/nhtamup/public_html/
    - cd $DEPLOYPATH
    - /usr/local/bin/php /usr/local/bin/composer install --no-dev --optimize-autoloader --no-interaction
    - /usr/local/bin/php artisan migrate --force
    - /usr/local/bin/php artisan cache:clear
    - /usr/local/bin/php artisan config:cache
    - /usr/local/bin/php artisan route:cache
    - /usr/local/bin/php artisan view:cache
    - chmod -R 755 $DEPLOYPATH/storage
    - chmod -R 755 $DEPLOYPATH/bootstrap/cache
